### PR TITLE
additional blackjack2 file for ideas

### PR DESCRIPTION
**Pull request by stephenh67**

### CODE REVIEW

**Comment by AmarTrivedi5** [comment]
It looks really good, but just kinda thinking if this takes away the whole collaborative and learning aspect to this project? If you just did all that on your own anyway in another file.

**Comment by AmarTrivedi5** [comment]
^ Am just talking about the second file thing. Great work with the commits to the main blackjack!

**Review by AmarTrivedi5 — APPROVED** [review]
Good idea with moving the functions out of the loop, so we only have to define them once! Tested and it ran well!

**Comment by stephenh67** [comment]
Its a short enough file I just thought ild throw it in as a sample to compare with, ie using f" " to format etc, feel free to remove it...

**Comment by stephenh67** [comment]
@AmarTrivedi5 you'll need to merge it if ok, as I don't have write access

**Comment by AmarTrivedi5** [comment]
Sorry, I don't have write access either. Might have to wait for Alex.

**Comment by stephenh67** [comment]
I would like to suggest we have one or more scratch files so we can show each other samples without pushing them directly to main for ideas to work towards.... I've found another program with an interesting twist, a text display of cards.... might be a feature to work in when suits are added

**Comment by stephenh67** [comment]
@AmarTrivedi5 After taking a closer look I think the intent was for this file to be worked on in the Practice repo that was set up after this one. I'm going to push the most recent

**Pull request closed without merging**
